(()=>{
  const BLOG_URL='https://blog.naver.com/pet-travel';
  const $=(s)=>document.querySelector(s), $$=(s)=>[...document.querySelectorAll(s)];
  const style=document.createElement('style');
  style.textContent=`header .wrap{display:flex;align-items:center;justify-content:space-between;gap:16px}.dq-tools{display:flex;align-items:center;justify-content:flex-end;gap:8px;flex-wrap:wrap}.dq-counter{display:flex;gap:8px;align-items:center;padding:8px 10px;border:1px solid #dbe5f5;border-radius:12px;background:#fff;color:#526070;font-size:11px;font-weight:800;white-space:nowrap}.dq-counter b{color:#0b1f4a;font-size:13px}.dq-counter .dq-total{border-left:1px solid #dbe5f5;padding-left:8px}.dq-blog,.dq-lang{display:inline-flex;align-items:center;justify-content:center;height:34px;border-radius:10px;padding:0 11px;border:1px solid #c9d8f2;background:#fff;color:#0b1f4a;font-size:12px;font-weight:900;text-decoration:none;cursor:pointer}.dq-blog{background:#03c75a;border-color:#03c75a;color:#fff}.dq-lang{width:40px}@media(max-width:640px){header .wrap{align-items:flex-start}.dq-tools{gap:5px}.dq-counter{order:3;width:100%;justify-content:center;padding:7px}.dq-blog,.dq-lang{height:32px;padding:0 9px}.brand{font-size:14px}.brand small{font-size:9px}}`;
  document.head.append(style);
  const header=$('header .wrap'); if(!header) return;
  const tools=document.createElement('div'); tools.className='dq-tools';
  tools.innerHTML='<a class="dq-blog" href="'+BLOG_URL+'" target="_blank" rel="noopener">네이버 블로그</a><button class="dq-lang" type="button" aria-label="언어 변경">EN</button><div class="dq-counter"><span>오늘 <b id="dq-today">10</b></span><span class="dq-total">누적 <b id="dq-total">3,000</b></span></div>';
  header.append(tools);
  const day=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Seoul'});
  let v={};try{v=JSON.parse(localStorage.getItem('dq_visitor_display')||'{}')}catch(e){}
  if(v.day!==day){v={day,today:10,total:Math.max(3000,Number(v.total)||3000)}}
  if(!sessionStorage.getItem('dq_counted')){v.today+=1;v.total+=1;sessionStorage.setItem('dq_counted','1')}
  localStorage.setItem('dq_visitor_display',JSON.stringify(v));
  $('#dq-today').textContent=v.today.toLocaleString('ko-KR'); $('#dq-total').textContent=v.total.toLocaleString('ko-KR');
  const ko={blog:'네이버 블로그',today:'오늘',total:'누적',eyebrow:'반려동물 해외출국 전문',h1:'어디로 가시나요?<br>바로 준비해드릴게요.',lead:'목적지와 출국일만 입력하면 필요한 준비사항과 예상 견적을 바로 확인할 수 있습니다.',points:['수의사 직접 진행','수의사 직접 상담','해외 응급콜','빠른 출국 준비'],card:'해외출국 준비 확인',sub:'4가지만 입력해주세요.',labels:['출국 나라','동물등록(내장형) 여부','반려동물','출국 예정일'],button:'일정 및 금액 확인',call:'24시간 콜센터',address:'주소',store:'닥터검역 부산해외동물검역센터 실제 매장',interiors:['닥터검역 1 · 상담실 내부','닥터검역 2 · 진료·검역 준비 공간']};
  const en={blog:'Naver Blog',today:'Today',total:'Total',eyebrow:'PET OVERSEAS TRAVEL SPECIALIST',h1:'Where are you going?<br>We will prepare it for you.',lead:'Enter your destination and departure date to check the required steps and estimated cost.',points:['Veterinarian-led service','Veterinarian consultation','Overseas emergency call','Fast departure preparation'],card:'Overseas Travel Check',sub:'Please enter these 4 details.',labels:['Destination','Microchip registration','Pet','Departure date'],button:'Check schedule & estimate',call:'24-hour call center',address:'Address',store:'Dr. Quarantine Pet Travel Center',interiors:['Dr. Quarantine 1 · Consultation room','Dr. Quarantine 2 · Examination & preparation room']};
  let lang='ko'; function apply(l){const d=l==='en'?en:ko;lang=l;document.documentElement.lang=l;$('.dq-blog').textContent=d.blog;$('.dq-lang').textContent=l==='ko'?'EN':'KO';$('.dq-counter span:first-child').childNodes[0].textContent=d.today+' ';$('.dq-total').childNodes[0].textContent=d.total+' ';$('.eyebrow').textContent=d.eyebrow;$('.intro-panel h1').innerHTML=d.h1;$('.lead').textContent=d.lead;$$('.point span').forEach((x,i)=>x.textContent=d.points[i]);$('.card h2').textContent=d.card;$('.card .sub').textContent=d.sub;$$('.form-grid label').forEach((x,i)=>x.textContent=d.labels[i]);$('.card>button').textContent=d.button;const info=$('.center-info');if(info)info.innerHTML='<div><b>'+d.call+'</b> : <a href="tel:01064957571">010-6495-7571</a></div><div><b>'+d.address+'</b> : 부산시 수영구 수영로 576 지하상가 E존 <span>(수영역에서 1분)</span></div>';$('.store-photo-caption').textContent=d.store;$$('.interior-photo span').forEach((x,i)=>x.textContent=d.interiors[i]);}
  $('.dq-lang').addEventListener('click',()=>apply(lang==='ko'?'en':'ko'));apply('ko');
})();
